apiVersion: apps/v1
kind: Deployment
metadata:
  name: country
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country
  template:
    metadata:
      labels:
        app: country
    spec:
      imagePullSecrets:
        - name: default-secret
      containers:
      - name: country
        image: swr.af-south-1.myhuaweicloud.com/ralf/country:96e07fc4dbb5f89ca5103431e64f88e1a1d5d5bc
        ports:
        - containerPort: 3001
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
