apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: default-secret
      containers:
      - name: frontend
        image: swr.ap-southeast-3.myhuaweicloud.com/ralf/frontend:96e07fc4dbb5f89ca5103431e64f88e1a1d5d5bc
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
