name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Log in to Huawei Cloud SWR
      id: build-image
      uses: huaweicloud/swr-login@v2.1.0
      with:
        access-key-id: ${{ secrets.ACCESSKEY }}
        access-key-secret: ${{ secrets.SECRETACCESSKEY }}
        region: ap-southeast-3     

    - name: Build and push Cuntry image
      run: |
        docker build -t swr.ap-southeast-3.myhuaweicloud.com/ralf/cuntry:${{ github.sha }} country
        docker push swr.ap-southeast-3.myhuaweicloud.com/ralf/cuntry:${{ github.sha }}
        echo "::set-output name=image::swr.ap-southeast-3.myhuaweicloud.com/ralf/cuntry:${{ github.sha }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.1.0
        with: 
            access_key_id: ${{ secrets.ACCESSKEY }} 
            secret_access_key: ${{ secrets.SECRETACCESSKEY }}
            region: 'ap-southeast-3'
            #project_id: '04eb02332a0025b92f00c0005dd31f24'


      - name: Deploy to CCI
        uses: huaweicloud/deploy-cci-action@v1.2.0
        id: deploy-to-cci
        with:
          namespace: 'dev-namespace-ralf'
          deployment: 'from-github'
          image: 'swr.ap-southeast-3.myhuaweicloud.com/ralf/cuntry:615eae68438c81715d08da8442799ab69a7175ec'
          # image: ${{ needs.build.outputs.image }}
          manifest: country/manifest/
